name: Build Ekstensiku
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew :src:all:googledrive:spotlessApply || true
          ./gradlew :src:all:googledrive:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Ekstensi-GoogleDrive
          path: "**/build/outputs/apk/debug/*.apk"
